kind: Deployment
apiVersion: apps/v1
metadata:
  name: docker-k8s-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: gjaseka/docker-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: docker-k8s-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: docker-k8s-demo